"""Target-neutral runtime contracts for converted automation logic."""

from .contracts import (
    CyclicIOProvider,
    ModuleService,
    ModuleStatus,
    ParameterOperation,
    ParameterRequest,
    ParameterResult,
    ParameterResultState,
    ParameterService,
)
from .cyclic_io import (
    ByteOrder,
    PackedCyclicIOContract,
    PackedField,
    PackedImage,
    PackedImageLayout,
    build_packed_cyclic_io_contract,
)
from .powerflex525_core import (
    PowerFlex525Core,
    PowerFlexCommandSource,
    PowerFlexCommands,
    PowerFlexCoreInput,
    PowerFlexCoreOutput,
    PowerFlexCoreState,
)
from .sys_module_core import (
    SysModuleCore,
    SysModuleModeWrite,
    SysModuleOutputs,
    SysModulePrescanResult,
    SysModuleScanResult,
    SysModuleSnapshot,
    SysModuleStatus,
    decode_entry_status,
)
from .sys_module_runtime import (
    SysModuleAdapter,
    SysModuleAdapterError,
    SysModuleRuntime,
    SysModuleRuntimeResult,
    SysModuleServiceFailure,
)

__all__ = [
    "ByteOrder",
    "CyclicIOProvider",
    "ModuleService",
    "ModuleStatus",
    "PackedCyclicIOContract",
    "PackedField",
    "PackedImage",
    "PackedImageLayout",
    "ParameterOperation",
    "ParameterRequest",
    "ParameterResult",
    "ParameterResultState",
    "ParameterService",
    "SysModuleCore",
    "SysModuleModeWrite",
    "SysModuleOutputs",
    "SysModulePrescanResult",
    "SysModuleScanResult",
    "SysModuleSnapshot",
    "SysModuleStatus",
    "SysModuleAdapter",
    "SysModuleAdapterError",
    "SysModuleRuntime",
    "SysModuleRuntimeResult",
    "SysModuleServiceFailure",
    "decode_entry_status",
    "PowerFlex525Core",
    "PowerFlexCommandSource",
    "PowerFlexCommands",
    "PowerFlexCoreInput",
    "PowerFlexCoreOutput",
    "PowerFlexCoreState",
    "build_packed_cyclic_io_contract",
]
