@startuml twinforge_domain_model

title TwinForge Domain Model

class Plant
class Controller
class Chassis
class Module
class Program
class Tag

Plant *-- Controller
Controller *-- Chassis
Chassis *-- Module

Controller *-- Program
Controller *-- Tag

@enduml
