"""Schneider-documented structures for standard Universal I/O ("T_U_...") Device DDTs.

Device DDTs are auto-generated by Control Expert from a configured module's DTM
and are not always serialized into a project export -- unlike a user-defined
DDT, a member path referencing one has no source-evidenced structure to prove
it against (see the resource variable / member path roadmap checkpoints for
the real corpus gap this closes). Every entry here is transcribed from
Schneider's own module manuals, cited by document reference and page; nothing
is inferred from how a project happens to use a field. Only fields the cited
table names unambiguously are included -- a table whose text extraction was
ambiguous or truncated is left out rather than guessed at.

This catalog only supplements member-path resolution (see
``analysis.graphical_bindings.member_path_context``); it is never merged into
a parsed project's own ``Controller.datatypes``, so nothing here is ever
reported as if a project actually captured it.

Sources:
- Modicon X80 - Discrete Input/Output Modules User Manual, 35012474, 12/2018, p.371.
- Modicon X80 - Analog Input/Output Modules User Manual, 35011978, 09/2020, p.261-262.
- Modicon M580 Safety Manual, QGH46982.08, p.58-59 (analog), p.87 (discrete in),
  p.117-118 (discrete relay out).
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DeviceDdtMember:
    name: str
    data_type_name: str


@dataclass(frozen=True)
class DeviceDdtDefinition:
    members: tuple[DeviceDdtMember, ...]
    source: str


def _members(*pairs: tuple[str, str]) -> tuple[DeviceDdtMember, ...]:
    return tuple(DeviceDdtMember(name, data_type) for name, data_type in pairs)


_X80_DISCRETE = "Modicon X80 - Discrete Input/Output Modules User Manual, 35012474, 12/2018, p.371"
_X80_ANALOG = "Modicon X80 - Analog Input/Output Modules User Manual, 35011978, 09/2020, p.261-262"
_M580_SAFETY_ANA = "Modicon M580 Safety Manual, QGH46982.08, p.58-59"
_M580_SAFETY_DIS_IN = "Modicon M580 Safety Manual, QGH46982.08, p.87"
_M580_SAFETY_DIS_ROUT = "Modicon M580 Safety Manual, QGH46982.08, p.117-118"

# The analog value substructure's field set is documented once, shared verbatim
# by both the "IN" and "OUT" channel structures (35011978 p.262); this project's
# model has no read/write-access distinction to tell the two copies apart by.
_ANA_VALUE_MEMBERS = _members(
    ("VALUE", "INT"), ("FORCED_VALUE", "INT"), ("FORCE_CMD", "BOOL"),
    ("FORCE_STATE", "BOOL"), ("TRUE_VALUE", "INT"),
)

DEVICE_DDT_CATALOG: dict[str, DeviceDdtDefinition] = {
    "T_U_DIS_STD_CH_IN": DeviceDdtDefinition(
        _members(("CH_HEALTH", "BOOL"), ("VALUE", "EBOOL")), _X80_DISCRETE),
    "T_U_DIS_STD_CH_OUT": DeviceDdtDefinition(
        _members(("CH_HEALTH", "BOOL"), ("VALUE", "EBOOL")), _X80_DISCRETE),
    "T_U_ANA_STD_CH_IN": DeviceDdtDefinition(
        _members(("FCT_TYPE", "WORD"), ("CH_HEALTH", "BOOL"), ("CH_WARNING", "BOOL"),
                  ("ANA", "T_U_ANA_VALUE_IN")),
        _X80_ANALOG),
    "T_U_ANA_STD_CH_OUT": DeviceDdtDefinition(
        _members(("FCT_TYPE", "WORD"), ("CH_HEALTH", "BOOL"), ("ANA", "T_U_ANA_VALUE_OUT")),
        _X80_ANALOG),
    "T_U_ANA_TEMP_CH_IN": DeviceDdtDefinition(
        _members(("FCT_TYPE", "WORD"), ("CH_HEALTH", "BOOL"), ("CH_WARNING", "BOOL"),
                  ("ANA", "T_U_ANA_VALUE_IN"), ("MEASURE_STS", "INT"), ("CJC_VALUE", "INT")),
        _X80_ANALOG),
    "T_U_ANA_VALUE_IN": DeviceDdtDefinition(_ANA_VALUE_MEMBERS, _X80_ANALOG),
    "T_U_ANA_VALUE_OUT": DeviceDdtDefinition(_ANA_VALUE_MEMBERS, _X80_ANALOG),
    "T_U_ANA_SIS_CH_IN": DeviceDdtDefinition(
        _members(("FCT_TYPE", "WORD"), ("CH_HEALTH", "BOOL"), ("VALUE", "INT"),
                  ("OOR", "BOOL"), ("IC", "BOOL")),
        _M580_SAFETY_ANA),
    "T_U_DIS_SIS_CH_IN": DeviceDdtDefinition(
        _members(("CH_HEALTH", "BOOL"), ("VALUE", "EBOOL"), ("OC", "BOOL"),
                  ("SC", "BOOL"), ("IC", "BOOL")),
        _M580_SAFETY_DIS_IN),
    "T_U_DIS_SIS_CH_ROUT": DeviceDdtDefinition(
        _members(("CH_HEALTH", "BOOL"), ("VALUE", "EBOOL"), ("TRUE_VALUE", "BOOL"),
                  ("IC", "BOOL"), ("CH_FBC", "BOOL"), ("CH_FBST", "BOOL")),
        _M580_SAFETY_DIS_ROUT),
}
