PROGRAM main
VAR
	CountPulse : bool AT %QX0.0;
	ResetCounter : bool AT %QX0.1;
	Done : bool AT %QX0.2;
	CounterEnabled : bool AT %QX0.3;
	Overflow : bool AT %QX0.4;
	CurrentCount : dint AT %MD0;
	CounterInstance : TF_CTU;
	Preset : dint := 3;
END_VAR

{
  "name": "main",
  "rungs": [
    {
      "id": "rung_main_e05257fc-c382-4294-a0a2-9bab6ac67cb7",
      "comment": "",
      "defaultBounds": [
        300,
        100
      ],
      "reactFlowViewport": [
        779,
        214
      ],
      "nodes": [
        {
          "id": "left-rail-rung_main_e05257fc-c382-4294-a0a2-9bab6ac67cb7",
          "type": "powerRail",
          "position": {
            "x": 0,
            "y": 30
          },
          "height": 40,
          "width": 3,
          "measured": {
            "width": 3,
            "height": 40
          },
          "draggable": false,
          "selectable": false,
          "data": {
            "handles": [
              {
                "glbPosition": {
                  "x": 3,
                  "y": 50
                },
                "relPosition": {
                  "x": 3,
                  "y": 20
                },
                "id": "left-rail",
                "position": "right",
                "type": "source",
                "isConnectable": false,
                "style": {
                  "top": 20,
                  "right": -3
                }
              }
            ],
            "inputHandles": [],
            "outputHandles": [
              {
                "glbPosition": {
                  "x": 3,
                  "y": 50
                },
                "relPosition": {
                  "x": 3,
                  "y": 20
                },
                "id": "left-rail",
                "position": "right",
                "type": "source",
                "isConnectable": false,
                "style": {
                  "top": 20,
                  "right": -3
                }
              }
            ],
            "outputConnector": {
              "glbPosition": {
                "x": 3,
                "y": 50
              },
              "relPosition": {
                "x": 3,
                "y": 20
              },
              "id": "left-rail",
              "position": "right",
              "type": "source",
              "isConnectable": false,
              "style": {
                "top": 20,
                "right": -3
              }
            },
            "numericId": "9689847",
            "variant": "left",
            "variable": {
              "name": ""
            },
            "executionOrder": 0,
            "draggable": false,
            "selectable": false,
            "deletable": false,
            "hasDivergence": false
          }
        },
        {
          "id": "CONTACT_ea2146c1-0c6a-4512-b021-650a89c405c4",
          "type": "contact",
          "position": {
            "x": 68,
            "y": 38
          },
          "height": 24,
          "width": 24,
          "measured": {
            "width": 24,
            "height": 24
          },
          "draggable": true,
          "selectable": true,
          "data": {
            "handles": [
              {
                "glbPosition": {
                  "x": 68,
                  "y": 50
                },
                "relPosition": {
                  "x": 0,
                  "y": 12
                },
                "id": "input",
                "position": "left",
                "isConnectable": false,
                "type": "target",
                "style": {
                  "left": -3
                }
              },
              {
                "glbPosition": {
                  "x": 92,
                  "y": 50
                },
                "relPosition": {
                  "x": 24,
                  "y": 12
                },
                "id": "output",
                "position": "right",
                "isConnectable": false,
                "type": "source",
                "style": {
                  "right": -3
                }
              }
            ],
            "variant": "default",
            "inputHandles": [
              {
                "glbPosition": {
                  "x": 68,
                  "y": 50
                },
                "relPosition": {
                  "x": 0,
                  "y": 12
                },
                "id": "input",
                "position": "left",
                "isConnectable": false,
                "type": "target",
                "style": {
                  "left": -3
                }
              }
            ],
            "outputHandles": [
              {
                "glbPosition": {
                  "x": 92,
                  "y": 50
                },
                "relPosition": {
                  "x": 24,
                  "y": 12
                },
                "id": "output",
                "position": "right",
                "isConnectable": false,
                "type": "source",
                "style": {
                  "right": -3
                }
              }
            ],
            "inputConnector": {
              "glbPosition": {
                "x": 68,
                "y": 50
              },
              "relPosition": {
                "x": 0,
                "y": 12
              },
              "id": "input",
              "position": "left",
              "isConnectable": false,
              "type": "target",
              "style": {
                "left": -3
              }
            },
            "outputConnector": {
              "glbPosition": {
                "x": 92,
                "y": 50
              },
              "relPosition": {
                "x": 24,
                "y": 12
              },
              "id": "output",
              "position": "right",
              "isConnectable": false,
              "type": "source",
              "style": {
                "right": -3
              }
            },
            "numericId": "6647795",
            "variable": {
              "name": "CountPulse",
              "class": "local",
              "type": {
                "definition": "base-type",
                "value": "bool"
              },
              "location": "%QX0.0",
              "initialValue": null,
              "documentation": "",
              "debug": false
            },
            "executionOrder": 0,
            "draggable": true,
            "selectable": true,
            "deletable": true,
            "hasDivergence": false
          }
        },
        {
          "id": "BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9",
          "type": "block",
          "position": {
            "x": 257,
            "y": 14
          },
          "height": 180,
          "width": 216,
          "measured": {
            "width": 216,
            "height": 180
          },
          "draggable": true,
          "selectable": true,
          "data": {
            "handles": [
              {
                "glbPosition": {
                  "x": 257,
                  "y": 50
                },
                "relPosition": {
                  "x": 0,
                  "y": 36
                },
                "id": "CU",
                "position": "left",
                "type": "target",
                "isConnectable": false,
                "style": {
                  "top": 36,
                  "left": 0
                }
              },
              {
                "glbPosition": {
                  "x": 257,
                  "y": 90
                },
                "relPosition": {
                  "x": 0,
                  "y": 76
                },
                "id": "RESET",
                "position": "left",
                "type": "target",
                "isConnectable": false,
                "style": {
                  "top": 76,
                  "left": 0
                }
              },
              {
                "glbPosition": {
                  "x": 257,
                  "y": 130
                },
                "relPosition": {
                  "x": 0,
                  "y": 116
                },
                "id": "PV",
                "position": "left",
                "type": "target",
                "isConnectable": false,
                "style": {
                  "top": 116,
                  "left": 0
                }
              },
              {
                "glbPosition": {
                  "x": 473,
                  "y": 50
                },
                "relPosition": {
                  "x": 216,
                  "y": 36
                },
                "id": "Q",
                "position": "right",
                "type": "source",
                "isConnectable": false,
                "style": {
                  "top": 36,
                  "right": 0
                }
              },
              {
                "glbPosition": {
                  "x": 473,
                  "y": 90
                },
                "relPosition": {
                  "x": 216,
                  "y": 76
                },
                "id": "CV",
                "position": "right",
                "type": "source",
                "isConnectable": false,
                "style": {
                  "top": 76,
                  "right": 0
                }
              },
              {
                "glbPosition": {
                  "x": 473,
                  "y": 130
                },
                "relPosition": {
                  "x": 216,
                  "y": 116
                },
                "id": "CountEnabled",
                "position": "right",
                "type": "source",
                "isConnectable": false,
                "style": {
                  "top": 116,
                  "right": 0
                }
              },
              {
                "glbPosition": {
                  "x": 473,
                  "y": 170
                },
                "relPosition": {
                  "x": 216,
                  "y": 156
                },
                "id": "OV",
                "position": "right",
                "type": "source",
                "isConnectable": false,
                "style": {
                  "top": 156,
                  "right": 0
                }
              }
            ],
            "inputHandles": [
              {
                "glbPosition": {
                  "x": 257,
                  "y": 50
                },
                "relPosition": {
                  "x": 0,
                  "y": 36
                },
                "id": "CU",
                "position": "left",
                "type": "target",
                "isConnectable": false,
                "style": {
                  "top": 36,
                  "left": 0
                }
              },
              {
                "glbPosition": {
                  "x": 257,
                  "y": 90
                },
                "relPosition": {
                  "x": 0,
                  "y": 76
                },
                "id": "RESET",
                "position": "left",
                "type": "target",
                "isConnectable": false,
                "style": {
                  "top": 76,
                  "left": 0
                }
              },
              {
                "glbPosition": {
                  "x": 257,
                  "y": 130
                },
                "relPosition": {
                  "x": 0,
                  "y": 116
                },
                "id": "PV",
                "position": "left",
                "type": "target",
                "isConnectable": false,
                "style": {
                  "top": 116,
                  "left": 0
                }
              }
            ],
            "outputHandles": [
              {
                "glbPosition": {
                  "x": 473,
                  "y": 50
                },
                "relPosition": {
                  "x": 216,
                  "y": 36
                },
                "id": "Q",
                "position": "right",
                "type": "source",
                "isConnectable": false,
                "style": {
                  "top": 36,
                  "right": 0
                }
              },
              {
                "glbPosition": {
                  "x": 473,
                  "y": 90
                },
                "relPosition": {
                  "x": 216,
                  "y": 76
                },
                "id": "CV",
                "position": "right",
                "type": "source",
                "isConnectable": false,
                "style": {
                  "top": 76,
                  "right": 0
                }
              },
              {
                "glbPosition": {
                  "x": 473,
                  "y": 130
                },
                "relPosition": {
                  "x": 216,
                  "y": 116
                },
                "id": "CountEnabled",
                "position": "right",
                "type": "source",
                "isConnectable": false,
                "style": {
                  "top": 116,
                  "right": 0
                }
              },
              {
                "glbPosition": {
                  "x": 473,
                  "y": 170
                },
                "relPosition": {
                  "x": 216,
                  "y": 156
                },
                "id": "OV",
                "position": "right",
                "type": "source",
                "isConnectable": false,
                "style": {
                  "top": 156,
                  "right": 0
                }
              }
            ],
            "inputConnector": {
              "glbPosition": {
                "x": 257,
                "y": 50
              },
              "relPosition": {
                "x": 0,
                "y": 36
              },
              "id": "CU",
              "position": "left",
              "type": "target",
              "isConnectable": false,
              "style": {
                "top": 36,
                "left": 0
              }
            },
            "outputConnector": {
              "glbPosition": {
                "x": 473,
                "y": 50
              },
              "relPosition": {
                "x": 216,
                "y": 36
              },
              "id": "Q",
              "position": "right",
              "type": "source",
              "isConnectable": false,
              "style": {
                "top": 36,
                "right": 0
              }
            },
            "numericId": "4042026",
            "variant": {
              "name": "TF_CTU",
              "type": "function-block",
              "variables": [
                {
                  "name": "CU",
                  "class": "input",
                  "type": {
                    "definition": "base-type",
                    "value": "BOOL"
                  }
                },
                {
                  "name": "RESET",
                  "class": "input",
                  "type": {
                    "definition": "base-type",
                    "value": "BOOL"
                  }
                },
                {
                  "name": "PV",
                  "class": "input",
                  "type": {
                    "definition": "base-type",
                    "value": "DINT"
                  }
                },
                {
                  "name": "Q",
                  "class": "output",
                  "type": {
                    "definition": "base-type",
                    "value": "BOOL"
                  }
                },
                {
                  "name": "CV",
                  "class": "output",
                  "type": {
                    "definition": "base-type",
                    "value": "DINT"
                  }
                },
                {
                  "name": "CountEnabled",
                  "class": "output",
                  "type": {
                    "definition": "base-type",
                    "value": "BOOL"
                  }
                },
                {
                  "name": "OV",
                  "class": "output",
                  "type": {
                    "definition": "base-type",
                    "value": "BOOL"
                  }
                },
                {
                  "name": "WasCU",
                  "class": "local",
                  "type": {
                    "definition": "base-type",
                    "value": "BOOL"
                  }
                }
              ],
              "documentation": "",
              "extensible": false
            },
            "variable": {
              "name": "CounterInstance",
              "class": "local",
              "type": {
                "definition": "derived",
                "value": "TF_CTU"
              },
              "location": "",
              "initialValue": null,
              "documentation": "",
              "debug": false
            },
            "executionOrder": 0,
            "executionControl": false,
            "lockExecutionControl": false,
            "connectedVariables": [
              {
                "handleId": "RESET",
                "type": "input",
                "variable": {
                  "name": "ResetCounter",
                  "class": "local",
                  "type": {
                    "definition": "base-type",
                    "value": "bool"
                  },
                  "location": "%QX0.1",
                  "initialValue": null,
                  "documentation": "",
                  "debug": false
                }
              },
              {
                "handleId": "PV",
                "type": "input",
                "variable": {
                  "name": "Preset",
                  "class": "local",
                  "type": {
                    "definition": "base-type",
                    "value": "dint"
                  },
                  "location": "",
                  "initialValue": "3",
                  "documentation": "",
                  "debug": false
                }
              },
              {
                "handleId": "CV",
                "type": "output",
                "variable": {
                  "name": "CurrentCount",
                  "class": "local",
                  "type": {
                    "definition": "base-type",
                    "value": "dint"
                  },
                  "location": "%MD0",
                  "initialValue": null,
                  "documentation": "",
                  "debug": false
                }
              },
              {
                "handleId": "OV",
                "type": "output",
                "variable": {
                  "name": "Overflow",
                  "class": "local",
                  "type": {
                    "definition": "base-type",
                    "value": "bool"
                  },
                  "location": "%QX0.4",
                  "initialValue": null,
                  "documentation": "",
                  "debug": false
                }
              },
              {
                "handleId": "CountEnabled",
                "type": "output",
                "variable": {
                  "name": "CounterEnabled",
                  "class": "local",
                  "type": {
                    "definition": "base-type",
                    "value": "bool"
                  },
                  "location": "%QX0.3",
                  "initialValue": null,
                  "documentation": "",
                  "debug": false
                }
              }
            ],
            "draggable": true,
            "selectable": true,
            "deletable": true,
            "hasDivergence": false
          }
        },
        {
          "id": "COIL_acd5e76f-c1f1-4a0c-a17c-01d423741b03",
          "type": "coil",
          "position": {
            "x": 638,
            "y": 38
          },
          "height": 24,
          "width": 28,
          "measured": {
            "width": 28,
            "height": 24
          },
          "draggable": true,
          "selectable": true,
          "data": {
            "handles": [
              {
                "glbPosition": {
                  "x": 638,
                  "y": 50
                },
                "relPosition": {
                  "x": 0,
                  "y": 12
                },
                "id": "input",
                "position": "left",
                "isConnectable": false,
                "type": "target",
                "style": {
                  "left": -3
                }
              },
              {
                "glbPosition": {
                  "x": 666,
                  "y": 50
                },
                "relPosition": {
                  "x": 28,
                  "y": 12
                },
                "id": "output",
                "position": "right",
                "isConnectable": false,
                "type": "source",
                "style": {
                  "right": -3
                }
              }
            ],
            "variant": "default",
            "inputHandles": [
              {
                "glbPosition": {
                  "x": 638,
                  "y": 50
                },
                "relPosition": {
                  "x": 0,
                  "y": 12
                },
                "id": "input",
                "position": "left",
                "isConnectable": false,
                "type": "target",
                "style": {
                  "left": -3
                }
              }
            ],
            "outputHandles": [
              {
                "glbPosition": {
                  "x": 666,
                  "y": 50
                },
                "relPosition": {
                  "x": 28,
                  "y": 12
                },
                "id": "output",
                "position": "right",
                "isConnectable": false,
                "type": "source",
                "style": {
                  "right": -3
                }
              }
            ],
            "inputConnector": {
              "glbPosition": {
                "x": 638,
                "y": 50
              },
              "relPosition": {
                "x": 0,
                "y": 12
              },
              "id": "input",
              "position": "left",
              "isConnectable": false,
              "type": "target",
              "style": {
                "left": -3
              }
            },
            "outputConnector": {
              "glbPosition": {
                "x": 666,
                "y": 50
              },
              "relPosition": {
                "x": 28,
                "y": 12
              },
              "id": "output",
              "position": "right",
              "isConnectable": false,
              "type": "source",
              "style": {
                "right": -3
              }
            },
            "numericId": "7249947",
            "variable": {
              "name": "Done",
              "class": "local",
              "type": {
                "definition": "base-type",
                "value": "bool"
              },
              "location": "%QX0.2",
              "initialValue": null,
              "documentation": "",
              "debug": false
            },
            "executionOrder": 0,
            "draggable": true,
            "selectable": true,
            "deletable": true
          }
        },
        {
          "id": "right-rail-rung_main_e05257fc-c382-4294-a0a2-9bab6ac67cb7",
          "type": "powerRail",
          "position": {
            "x": 776,
            "y": 30
          },
          "height": 40,
          "width": 3,
          "measured": {
            "width": 3,
            "height": 40
          },
          "draggable": false,
          "selectable": false,
          "data": {
            "handles": [
              {
                "glbPosition": {
                  "x": 297,
                  "y": 50
                },
                "relPosition": {
                  "x": 3,
                  "y": 20
                },
                "id": "right-rail",
                "position": "left",
                "type": "target",
                "isConnectable": false,
                "style": {
                  "top": 20,
                  "left": -3
                },
                "x": 776
              }
            ],
            "inputHandles": [
              {
                "glbPosition": {
                  "x": 297,
                  "y": 50
                },
                "relPosition": {
                  "x": 3,
                  "y": 20
                },
                "id": "right-rail",
                "position": "left",
                "type": "target",
                "isConnectable": false,
                "style": {
                  "top": 20,
                  "left": -3
                }
              }
            ],
            "outputHandles": [],
            "inputConnector": {
              "glbPosition": {
                "x": 297,
                "y": 50
              },
              "relPosition": {
                "x": 3,
                "y": 20
              },
              "id": "right-rail",
              "position": "left",
              "type": "target",
              "isConnectable": false,
              "style": {
                "top": 20,
                "left": -3
              }
            },
            "numericId": "3663379",
            "variant": "right",
            "variable": {
              "name": ""
            },
            "executionOrder": 0,
            "draggable": false,
            "selectable": false,
            "deletable": false,
            "hasDivergence": false
          }
        },
        {
          "id": "VARIABLE_87e64153-16b4-4b2d-bfc8-7b97cdf82294",
          "type": "variable",
          "position": {
            "x": 147,
            "y": 74
          },
          "height": 32,
          "width": 80,
          "measured": {
            "width": 80,
            "height": 32
          },
          "draggable": false,
          "selectable": true,
          "data": {
            "handles": [
              {
                "glbPosition": {
                  "x": 307,
                  "y": 90
                },
                "relPosition": {
                  "x": 80,
                  "y": 16
                },
                "id": "output",
                "position": "right",
                "isConnectable": false,
                "type": "source"
              }
            ],
            "inputHandles": [],
            "outputHandles": [
              {
                "glbPosition": {
                  "x": 307,
                  "y": 90
                },
                "relPosition": {
                  "x": 80,
                  "y": 16
                },
                "id": "output",
                "position": "right",
                "isConnectable": false,
                "type": "source"
              }
            ],
            "outputConnector": {
              "glbPosition": {
                "x": 307,
                "y": 90
              },
              "relPosition": {
                "x": 80,
                "y": 16
              },
              "id": "output",
              "position": "right",
              "isConnectable": false,
              "type": "source"
            },
            "numericId": "5960235",
            "variable": {
              "name": "ResetCounter",
              "class": "local",
              "type": {
                "definition": "base-type",
                "value": "bool"
              },
              "location": "%QX0.1",
              "initialValue": null,
              "documentation": "",
              "debug": false,
              "id": "broken-VARIABLE_87e64153-16b4-4b2d-bfc8-7b97cdf82294"
            },
            "executionOrder": 0,
            "variant": "input",
            "block": {
              "id": "BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9",
              "handleId": "RESET",
              "variableType": {
                "name": "RESET",
                "class": "input",
                "type": {
                  "definition": "base-type",
                  "value": "BOOL"
                }
              }
            },
            "draggable": false,
            "selectable": true,
            "deletable": false,
            "wrongVariable": true
          }
        },
        {
          "id": "VARIABLE_11aab461-c2de-404b-8db2-9a6db7cd7918",
          "type": "variable",
          "position": {
            "x": 147,
            "y": 114
          },
          "height": 32,
          "width": 80,
          "measured": {
            "width": 80,
            "height": 32
          },
          "draggable": false,
          "selectable": true,
          "data": {
            "handles": [
              {
                "glbPosition": {
                  "x": 307,
                  "y": 130
                },
                "relPosition": {
                  "x": 80,
                  "y": 16
                },
                "id": "output",
                "position": "right",
                "isConnectable": false,
                "type": "source"
              }
            ],
            "inputHandles": [],
            "outputHandles": [
              {
                "glbPosition": {
                  "x": 307,
                  "y": 130
                },
                "relPosition": {
                  "x": 80,
                  "y": 16
                },
                "id": "output",
                "position": "right",
                "isConnectable": false,
                "type": "source"
              }
            ],
            "outputConnector": {
              "glbPosition": {
                "x": 307,
                "y": 130
              },
              "relPosition": {
                "x": 80,
                "y": 16
              },
              "id": "output",
              "position": "right",
              "isConnectable": false,
              "type": "source"
            },
            "numericId": "2848574",
            "variable": {
              "name": "Preset",
              "class": "local",
              "type": {
                "definition": "base-type",
                "value": "dint"
              },
              "location": "",
              "initialValue": "3",
              "documentation": "",
              "debug": false,
              "id": "broken-VARIABLE_11aab461-c2de-404b-8db2-9a6db7cd7918"
            },
            "executionOrder": 0,
            "variant": "input",
            "block": {
              "id": "BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9",
              "handleId": "PV",
              "variableType": {
                "name": "PV",
                "class": "input",
                "type": {
                  "definition": "base-type",
                  "value": "DINT"
                }
              }
            },
            "draggable": false,
            "selectable": true,
            "deletable": false,
            "wrongVariable": true
          }
        },
        {
          "id": "VARIABLE_5875450d-9754-4f5e-ae6a-60a93ee160db",
          "type": "variable",
          "position": {
            "x": 503,
            "y": 74
          },
          "height": 32,
          "width": 80,
          "measured": {
            "width": 80,
            "height": 32
          },
          "draggable": false,
          "selectable": true,
          "data": {
            "handles": [
              {
                "glbPosition": {
                  "x": 503,
                  "y": 90
                },
                "relPosition": {
                  "x": 0,
                  "y": 16
                },
                "id": "input",
                "position": "left",
                "isConnectable": false,
                "type": "target"
              }
            ],
            "inputHandles": [
              {
                "glbPosition": {
                  "x": 503,
                  "y": 90
                },
                "relPosition": {
                  "x": 0,
                  "y": 16
                },
                "id": "input",
                "position": "left",
                "isConnectable": false,
                "type": "target"
              }
            ],
            "outputHandles": [],
            "inputConnector": {
              "glbPosition": {
                "x": 503,
                "y": 90
              },
              "relPosition": {
                "x": 0,
                "y": 16
              },
              "id": "input",
              "position": "left",
              "isConnectable": false,
              "type": "target"
            },
            "numericId": "4682107",
            "variable": {
              "name": "CurrentCount",
              "class": "local",
              "type": {
                "definition": "base-type",
                "value": "dint"
              },
              "location": "%MD0",
              "initialValue": null,
              "documentation": "",
              "debug": false,
              "id": "broken-VARIABLE_5875450d-9754-4f5e-ae6a-60a93ee160db"
            },
            "executionOrder": 0,
            "variant": "output",
            "block": {
              "id": "BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9",
              "handleId": "CV",
              "variableType": {
                "name": "CV",
                "class": "output",
                "type": {
                  "definition": "base-type",
                  "value": "DINT"
                }
              }
            },
            "draggable": false,
            "selectable": true,
            "deletable": false,
            "wrongVariable": true
          }
        },
        {
          "id": "VARIABLE_410dc632-8436-4fa7-8075-61d3d63572dc",
          "type": "variable",
          "position": {
            "x": 503,
            "y": 114
          },
          "height": 32,
          "width": 80,
          "measured": {
            "width": 80,
            "height": 32
          },
          "draggable": false,
          "selectable": true,
          "data": {
            "handles": [
              {
                "glbPosition": {
                  "x": 503,
                  "y": 130
                },
                "relPosition": {
                  "x": 0,
                  "y": 16
                },
                "id": "input",
                "position": "left",
                "isConnectable": false,
                "type": "target"
              }
            ],
            "inputHandles": [
              {
                "glbPosition": {
                  "x": 503,
                  "y": 130
                },
                "relPosition": {
                  "x": 0,
                  "y": 16
                },
                "id": "input",
                "position": "left",
                "isConnectable": false,
                "type": "target"
              }
            ],
            "outputHandles": [],
            "inputConnector": {
              "glbPosition": {
                "x": 503,
                "y": 130
              },
              "relPosition": {
                "x": 0,
                "y": 16
              },
              "id": "input",
              "position": "left",
              "isConnectable": false,
              "type": "target"
            },
            "numericId": "6097433",
            "variable": {
              "name": "CounterEnabled",
              "class": "local",
              "type": {
                "definition": "base-type",
                "value": "bool"
              },
              "location": "%QX0.3",
              "initialValue": null,
              "documentation": "",
              "debug": false,
              "id": "broken-VARIABLE_410dc632-8436-4fa7-8075-61d3d63572dc"
            },
            "executionOrder": 0,
            "variant": "output",
            "block": {
              "id": "BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9",
              "handleId": "CountEnabled",
              "variableType": {
                "name": "CountEnabled",
                "class": "output",
                "type": {
                  "definition": "base-type",
                  "value": "BOOL"
                }
              }
            },
            "draggable": false,
            "selectable": true,
            "deletable": false,
            "wrongVariable": true
          }
        },
        {
          "id": "VARIABLE_8c95cc4e-7cd2-45f5-8236-412bd1fccd18",
          "type": "variable",
          "position": {
            "x": 503,
            "y": 154
          },
          "height": 32,
          "width": 80,
          "measured": {
            "width": 80,
            "height": 32
          },
          "draggable": false,
          "selectable": true,
          "data": {
            "handles": [
              {
                "glbPosition": {
                  "x": 503,
                  "y": 170
                },
                "relPosition": {
                  "x": 0,
                  "y": 16
                },
                "id": "input",
                "position": "left",
                "isConnectable": false,
                "type": "target"
              }
            ],
            "inputHandles": [
              {
                "glbPosition": {
                  "x": 503,
                  "y": 170
                },
                "relPosition": {
                  "x": 0,
                  "y": 16
                },
                "id": "input",
                "position": "left",
                "isConnectable": false,
                "type": "target"
              }
            ],
            "outputHandles": [],
            "inputConnector": {
              "glbPosition": {
                "x": 503,
                "y": 170
              },
              "relPosition": {
                "x": 0,
                "y": 16
              },
              "id": "input",
              "position": "left",
              "isConnectable": false,
              "type": "target"
            },
            "numericId": "9219355",
            "variable": {
              "name": "Overflow",
              "class": "local",
              "type": {
                "definition": "base-type",
                "value": "bool"
              },
              "location": "%QX0.4",
              "initialValue": null,
              "documentation": "",
              "debug": false,
              "id": "broken-VARIABLE_8c95cc4e-7cd2-45f5-8236-412bd1fccd18"
            },
            "executionOrder": 0,
            "variant": "output",
            "block": {
              "id": "BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9",
              "handleId": "OV",
              "variableType": {
                "name": "OV",
                "class": "output",
                "type": {
                  "definition": "base-type",
                  "value": "BOOL"
                }
              }
            },
            "draggable": false,
            "selectable": true,
            "deletable": false,
            "wrongVariable": true
          }
        }
      ],
      "edges": [
        {
          "id": "e_left-rail-rung_main_e05257fc-c382-4294-a0a2-9bab6ac67cb7_CONTACT_ea2146c1-0c6a-4512-b021-650a89c405c4__left-rail_input",
          "source": "left-rail-rung_main_e05257fc-c382-4294-a0a2-9bab6ac67cb7",
          "sourceHandle": "left-rail",
          "target": "CONTACT_ea2146c1-0c6a-4512-b021-650a89c405c4",
          "targetHandle": "input"
        },
        {
          "id": "e_CONTACT_ea2146c1-0c6a-4512-b021-650a89c405c4_BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9__output_CU",
          "source": "CONTACT_ea2146c1-0c6a-4512-b021-650a89c405c4",
          "sourceHandle": "output",
          "target": "BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9",
          "targetHandle": "CU"
        },
        {
          "id": "e_BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9_COIL_acd5e76f-c1f1-4a0c-a17c-01d423741b03__Q_input",
          "source": "BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9",
          "sourceHandle": "Q",
          "target": "COIL_acd5e76f-c1f1-4a0c-a17c-01d423741b03",
          "targetHandle": "input"
        },
        {
          "id": "e_COIL_acd5e76f-c1f1-4a0c-a17c-01d423741b03_right-rail-rung_main_e05257fc-c382-4294-a0a2-9bab6ac67cb7__output_right-rail",
          "source": "COIL_acd5e76f-c1f1-4a0c-a17c-01d423741b03",
          "sourceHandle": "output",
          "target": "right-rail-rung_main_e05257fc-c382-4294-a0a2-9bab6ac67cb7",
          "targetHandle": "right-rail"
        },
        {
          "id": "e_VARIABLE_87e64153-16b4-4b2d-bfc8-7b97cdf82294_BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9__output_RESET",
          "source": "VARIABLE_87e64153-16b4-4b2d-bfc8-7b97cdf82294",
          "sourceHandle": "output",
          "target": "BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9",
          "targetHandle": "RESET"
        },
        {
          "id": "e_VARIABLE_11aab461-c2de-404b-8db2-9a6db7cd7918_BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9__output_PV",
          "source": "VARIABLE_11aab461-c2de-404b-8db2-9a6db7cd7918",
          "sourceHandle": "output",
          "target": "BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9",
          "targetHandle": "PV"
        },
        {
          "id": "e_BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9_VARIABLE_5875450d-9754-4f5e-ae6a-60a93ee160db__CV_input",
          "source": "BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9",
          "sourceHandle": "CV",
          "target": "VARIABLE_5875450d-9754-4f5e-ae6a-60a93ee160db",
          "targetHandle": "input"
        },
        {
          "id": "e_BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9_VARIABLE_410dc632-8436-4fa7-8075-61d3d63572dc__CountEnabled_input",
          "source": "BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9",
          "sourceHandle": "CountEnabled",
          "target": "VARIABLE_410dc632-8436-4fa7-8075-61d3d63572dc",
          "targetHandle": "input"
        },
        {
          "id": "e_BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9_VARIABLE_8c95cc4e-7cd2-45f5-8236-412bd1fccd18__OV_input",
          "source": "BLOCK_1d3ab404-8080-4306-a257-98a97f8fc0b9",
          "sourceHandle": "OV",
          "target": "VARIABLE_8c95cc4e-7cd2-45f5-8236-412bd1fccd18",
          "targetHandle": "input"
        }
      ]
    }
  ]
}
END_PROGRAM