"""
Rockwell Studio 5000 L5X specification.
"""

from .controller import (
    CONTROLLER_ATTRIBUTES,
    CONTROLLER_ELEMENTS,
    PRIMARY_ACTION_SET_ATTRIBUTES,
    REDUNDANCY_INFO_ATTRIBUTES,
    SAFETY_INFO_ELEMENTS,
    SAFETY_INFO_ATTRIBUTES,
    SECURITY_ATTRIBUTES,
    SECURITY_ELEMENTS,
)
from .datatypes import (
    DATATYPE_ATTRIBUTES,
    DATATYPE_ELEMENTS,
    DATATYPE_MEMBER_ATTRIBUTES,
    DATATYPE_MEMBER_ELEMENTS,
    DATATYPE_MEMBERS_ELEMENTS,
    DATATYPES_ELEMENTS,
)
from .modules import (
    MODULE_ATTRIBUTES,
    MODULE_ELEMENTS,
    MODULES_ELEMENTS,
)
from .programs import (
    PROGRAM_ATTRIBUTES,
    PROGRAM_ELEMENTS,
    PROGRAMS_ELEMENTS,
    RLL_CONTENT_ELEMENTS,
    ROUTINE_ATTRIBUTES,
    ROUTINE_ELEMENTS,
    ROUTINES_ELEMENTS,
    RUNG_ATTRIBUTES,
    RUNG_ELEMENTS,
)
from .reference import ReferenceType
from .spec import AttributeSpec, ElementSpec
from .tags import TAG_ATTRIBUTES, TAG_DATA_ATTRIBUTES, TAG_ELEMENTS, TAGS_ELEMENTS
from .tasks import (
    SCHEDULED_PROGRAM_ATTRIBUTES,
    SCHEDULED_PROGRAMS_ELEMENTS,
    TASK_ATTRIBUTES,
    TASK_ELEMENTS,
    TASKS_ELEMENTS,
)

__all__ = [
    "AttributeSpec",
    "ElementSpec",
    "CONTROLLER_ATTRIBUTES",
    "CONTROLLER_ELEMENTS",
    "DATATYPE_ATTRIBUTES",
    "DATATYPE_ELEMENTS",
    "DATATYPE_MEMBER_ATTRIBUTES",
    "DATATYPE_MEMBER_ELEMENTS",
    "DATATYPE_MEMBERS_ELEMENTS",
    "DATATYPES_ELEMENTS",
    "MODULE_ATTRIBUTES",
    "MODULE_ELEMENTS",
    "MODULES_ELEMENTS",
    "PROGRAM_ATTRIBUTES",
    "PROGRAM_ELEMENTS",
    "PROGRAMS_ELEMENTS",
    "PRIMARY_ACTION_SET_ATTRIBUTES",
    "REDUNDANCY_INFO_ATTRIBUTES",
    "ReferenceType",
    "RLL_CONTENT_ELEMENTS",
    "ROUTINE_ATTRIBUTES",
    "ROUTINE_ELEMENTS",
    "ROUTINES_ELEMENTS",
    "RUNG_ATTRIBUTES",
    "RUNG_ELEMENTS",
    "SCHEDULED_PROGRAM_ATTRIBUTES",
    "SCHEDULED_PROGRAMS_ELEMENTS",
    "SECURITY_ATTRIBUTES",
    "SECURITY_ELEMENTS",
    "TAG_ATTRIBUTES",
    "TAG_DATA_ATTRIBUTES",
    "TAG_ELEMENTS",
    "TAGS_ELEMENTS",
    "TASK_ATTRIBUTES",
    "TASK_ELEMENTS",
    "TASKS_ELEMENTS",
    "SAFETY_INFO_ATTRIBUTES",
    "SAFETY_INFO_ELEMENTS",
]
