CONTROLLER_ATTRIBUTES = {
    "Name",
    "ProcessorType",
    "MajorRev",
    "MinorRev",
    "ProjectCreationDate",
    "LastModifiedDate",
    "Use",
    "TargetName",
    "TargetType",
    "ContainsContext",
    "ExportDate",
    "ExportOptions",
}

CONTROLLER_ELEMENTS = {
    "Description",
    "RedundancyInfo",
    "Security",
    "SafetyInfo",
    "DataTypes",
    "Modules",
    "AddOnInstructionDefinitions",
    "Tags",
    "Programs",
    "Tasks",
    "ParameterConnections",
    "ParameterConnections",
    "Trends",
    "QuickWatchLists",
    "CommPorts",
    "CST",
    "WallClockTime",
    "PrimaryActionSet",
}
