"""Vendor-neutral executable intermediate representation."""

from .execution import apply_aoi_execution_semantics
from .lowering import lower_add_on_instruction, lower_structured_text
from .normalization import (
    IRNormalizationPolicy,
    IRNormalizationResult,
    normalize_reusable_unit,
)
from .model import (
    IRArrayDimension,
    IRAssignment,
    IRBinary,
    IRCall,
    IRCallStatement,
    IRDiagnostic,
    IRDirection,
    IRExit,
    IRExpression,
    IRIf,
    IRIfBranch,
    IRIndex,
    IRLiteral,
    IRLifecycle,
    IRMember,
    IRParameter,
    IRReference,
    IRReusableUnit,
    IRRoutine,
    IRRoutineRole,
    IRStatement,
    IRUnary,
    IRUnitKind,
    IRUnsupportedExpression,
    IRUnsupportedStatement,
    IRVariable,
    IRWallClockRead,
    IRWhile,
)

__all__ = [
    "IRArrayDimension",
    "IRAssignment",
    "IRBinary",
    "IRCall",
    "IRCallStatement",
    "IRDiagnostic",
    "IRDirection",
    "IRExit",
    "IRExpression",
    "IRIf",
    "IRIfBranch",
    "IRIndex",
    "IRLiteral",
    "IRLifecycle",
    "IRMember",
    "IRNormalizationPolicy",
    "IRNormalizationResult",
    "IRParameter",
    "IRReference",
    "IRReusableUnit",
    "IRRoutine",
    "IRRoutineRole",
    "IRStatement",
    "IRUnary",
    "IRUnitKind",
    "IRUnsupportedExpression",
    "IRUnsupportedStatement",
    "IRVariable",
    "IRWallClockRead",
    "IRWhile",
    "lower_add_on_instruction",
    "lower_structured_text",
    "normalize_reusable_unit",
    "apply_aoi_execution_semantics",
]
